import { CulturalEvent, Tradition, Relationship } from './types';

// DATA SOURCE: "Liminality, Lineage, and the Littoral" Thesis & Anthropological Tables
// This dataset represents a comprehensive mapping of Kerala's cultural system.

export const CULTURAL_EVENTS: CulturalEvent[] = [
  // --- 1. RITUAL ARTS & THEYYAM ---
  {
    id: 'ev_theyyam_general',
    name: 'Theyyam (General)',
    location: { lat: 12.00, lng: 75.35, region: 'North Malabar' },
    type: 'ritual',
    category: 'Ritual Art',
    description: 'A ritual dance where men invoke deities through trance, elaborate makeup, and headdresses.',
    significance: 'West Africa/Swahili Coast: Parallels with Bori and Peppo spirit possession cults.',
    seasonal_markers: ['October-May'],
    related_traditions: [],
    tags: ['trance', 'possession', 'tribal', 'indigenous'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_vishnumoorthy',
    name: 'Vishnumoorthy Theyyam',
    location: { lat: 12.18, lng: 75.20, region: 'Palottu Kavus, Kannur' },
    type: 'ritual',
    category: 'Deity',
    description: 'A popular Vaishnava Theyyam narrating the story of Narasimha.',
    significance: 'Hindu Mythology: Direct reenactment of the Narasimha avatar (Prahlada story) found pan-India.',
    seasonal_markers: ['Dry Season'],
    related_traditions: ['ev_theyyam_general'],
    tags: ['vaishnava', 'avatar', 'narasimha'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_muchilot',
    name: 'Muchilot Bhagavathi',
    location: { lat: 12.183, lng: 75.205, region: 'Karivellur, Kannur' },
    type: 'ritual',
    category: 'Deity',
    description: 'Goddess of learning and speech, originating from a Brahmin woman\'s suicide/apotheosis.',
    significance: 'Sati Traditions: Links to deification of women who commit ritual suicide in North India.',
    seasonal_markers: ['Summer', 'Perumkaliyattam'],
    related_traditions: ['ev_smarthavicharam'],
    tags: ['goddess', 'learning', 'apotheosis'],
    emotional_resonance: 'high',
    preservation_score: 90,
    dna_relationships: []
  },
  {
    id: 'ev_kathivanoor',
    name: 'Kathivanoor Veeran',
    location: { lat: 12.05, lng: 75.30, region: 'Mandampu Temple, Kannur' },
    type: 'ritual',
    category: 'Deity',
    description: 'A warrior hero deity known for martial prowess and tragic death.',
    significance: 'Hero Stones (Viragal): Parallels the hero-worship tradition of the Sangam era Tamilakam.',
    seasonal_markers: ['Variable'],
    related_traditions: ['ev_kalaripayattu'],
    tags: ['hero', 'martial', 'tragedy'],
    emotional_resonance: 'high',
    preservation_score: 88,
    dna_relationships: []
  },
  {
    id: 'ev_gulikan',
    name: 'Gulikan Theyyam',
    location: { lat: 11.90, lng: 75.40, region: 'North Malabar' },
    type: 'ritual',
    category: 'Deity',
    description: 'A representation of Yama (Death), providing comic relief and serious rituals.',
    significance: 'Bali: Similarities to the comedic/scary mask traditions in Balinese ritual theatre.',
    seasonal_markers: ['Variable'],
    related_traditions: [],
    tags: ['death', 'comedy', 'mask'],
    emotional_resonance: 'medium',
    preservation_score: 92,
    dna_relationships: []
  },
  {
    id: 'ev_pottan',
    name: 'Pottan Theyyam',
    location: { lat: 11.9, lng: 75.4, region: 'Kannur' },
    type: 'ritual',
    category: 'Deity',
    description: 'A manifestation of Shiva as a Chandala (outcaste) to test Sankara; speaks against caste.',
    significance: 'Bhakti Movement: Echoes the radical egalitarianism of Basavanna and North Indian Sants.',
    seasonal_markers: ['Harvest'],
    related_traditions: [],
    tags: ['anti-caste', 'shiva', 'fire-walking'],
    emotional_resonance: 'high',
    preservation_score: 85,
    dna_relationships: []
  },

  // --- 2. CLASSICAL & FOLK PERFORMANCE ---
  {
    id: 'ev_koodiyattam',
    name: 'Koodiyattam',
    location: { lat: 10.7052, lng: 76.2778, region: 'Kalamandalam / Moozhikkulam' },
    type: 'artform',
    category: 'Classical Theatre',
    description: 'The oldest surviving Sanskrit theatre; uses Netra Abhinaya (eye acting). UNESCO Heritage.',
    significance: 'Ancient India: Direct survival of the Natya Shastra performance tradition.',
    seasonal_markers: ['Year-round'],
    related_traditions: ['ev_kathakali'],
    tags: ['unesco', 'sanskrit', 'ancient'],
    emotional_resonance: 'medium',
    preservation_score: 85,
    dna_relationships: []
  },
  {
    id: 'ev_kathakali',
    name: 'Kathakali',
    location: { lat: 9.9656, lng: 76.2422, region: 'Kochi / Cheruthuruthy' },
    type: 'artform',
    category: 'Classical Dance',
    description: '"Story-Play" with elaborate makeup (Vesham) and mudras.',
    significance: 'Japan: Makeup and stylized gestures parallel Kabuki theatre.',
    seasonal_markers: ['Winter'],
    related_traditions: ['ev_kalaripayattu'],
    tags: ['dance-drama', 'makeup', 'iconic'],
    emotional_resonance: 'medium',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_mohiniyattam',
    name: 'Mohiniyattam',
    location: { lat: 10.76, lng: 76.28, region: 'Thrissur' },
    type: 'artform',
    category: 'Classical Dance',
    description: '"Dance of the Enchantress"; solo dance of graceful movements (Lasya).',
    significance: 'Tamil Nadu: Structural roots in the Devadasi traditions (Bharatanatyam).',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['female', 'lasya', 'dance'],
    emotional_resonance: 'medium',
    preservation_score: 90,
    dna_relationships: []
  },
  {
    id: 'ev_tholpavakoothu',
    name: 'Tholpavakoothu',
    location: { lat: 10.78, lng: 76.40, region: 'Koonathara, Palakkad' },
    type: 'ritual',
    category: 'Shadow Puppetry',
    description: 'Ritual shadow puppetry performed in Bhadrakali temples using leather puppets.',
    significance: 'Southeast Asia: Deep technical link to Wayang Kulit (Indonesia) and Nang Yai (Thailand).',
    seasonal_markers: ['Pooram Season'],
    related_traditions: [],
    tags: ['puppetry', 'shadow', 'temple'],
    emotional_resonance: 'medium',
    preservation_score: 60,
    dna_relationships: []
  },
  {
    id: 'ev_kalaripayattu',
    name: 'Kalaripayattu',
    location: { lat: 11.25, lng: 75.78, region: 'Kozhikode / Trivandrum' },
    type: 'artform',
    category: 'Martial Art',
    description: 'Ancient martial art focused on weaponry, flexibility, and Marma (vital points).',
    significance: 'China: Mythologically linked to the origin of Shaolin Kung Fu via Bodhidharma.',
    seasonal_markers: ['Monsoon'],
    related_traditions: ['ev_kathakali'],
    tags: ['martial', 'combat', 'healing'],
    emotional_resonance: 'high',
    preservation_score: 85,
    dna_relationships: []
  },
  {
    id: 'ev_chavittu',
    name: 'Chavittu Nadakam',
    location: { lat: 10.16, lng: 76.22, region: 'Gothuruthu / Fort Kochi' },
    type: 'artform',
    category: 'Christian Theatre',
    description: 'Stamping dance-drama of Latin Christians depicting Biblical tales (e.g., Charlemagne).',
    significance: 'Europe: Derived from Medieval Mystery Plays and European Opera; martial steps.',
    seasonal_markers: ['Christmas', 'Easter'],
    related_traditions: [],
    tags: ['christian', 'opera', 'latin'],
    emotional_resonance: 'medium',
    preservation_score: 65,
    dna_relationships: []
  },
  {
    id: 'ev_margamkali',
    name: 'Margamkali',
    location: { lat: 9.59, lng: 76.52, region: 'Kottayam' },
    type: 'artform',
    category: 'Christian Dance',
    description: 'Group dance of St. Thomas Christians performed around a lamp.',
    significance: 'Middle East: Roots in ancient Jewish wedding songs and Syrian liturgy.',
    seasonal_markers: ['Weddings'],
    related_traditions: [],
    tags: ['christian', 'syrian', 'dance'],
    emotional_resonance: 'medium',
    preservation_score: 80,
    dna_relationships: []
  },
  {
    id: 'ev_oppana',
    name: 'Oppana',
    location: { lat: 11.05, lng: 76.07, region: 'Malappuram' },
    type: 'artform',
    category: 'Muslim Dance',
    description: 'Bridal dance involving clapping and singing, popular in Malabar.',
    significance: 'Arabia: Resembles the Zikr traditions and folk dances of the Arabian Peninsula.',
    seasonal_markers: ['Weddings'],
    related_traditions: [],
    tags: ['muslim', 'mappila', 'bridal'],
    emotional_resonance: 'high',
    preservation_score: 90,
    dna_relationships: []
  },
  {
    id: 'ev_padayani',
    name: 'Padayani',
    location: { lat: 9.26, lng: 76.78, region: 'Kadammanitta' },
    type: 'ritual',
    category: 'Ritual Theatre',
    description: 'Mask dance using Kolams (areca sheath masks) to heal the community.',
    significance: 'Sri Lanka: Strong similarity to Kolam mask dances and exorcism rituals.',
    seasonal_markers: ['April'],
    related_traditions: [],
    tags: ['mask', 'healing', 'exorcism'],
    emotional_resonance: 'high',
    preservation_score: 75,
    dna_relationships: []
  },
  {
    id: 'ev_mudiyettu',
    name: 'Mudiyettu',
    location: { lat: 9.9, lng: 76.5, region: 'Pazhoor / Koratty' },
    type: 'ritual',
    category: 'Ritual Theatre',
    description: 'Enactment of Kali vs. Darika battle. UNESCO Intangible Heritage.',
    significance: 'Bengal: Thematic connection to the Kali worship and Durga traditions.',
    seasonal_markers: ['Summer'],
    related_traditions: [],
    tags: ['kali', 'unesco', 'floor-art'],
    emotional_resonance: 'high',
    preservation_score: 65,
    dna_relationships: []
  },
  {
    id: 'ev_pulikali',
    name: 'Pulikali',
    location: { lat: 10.52, lng: 76.21, region: 'Thrissur' },
    type: 'festival',
    category: 'Folk Art',
    description: '"Tiger Dance" performed during Onam with painted bodies.',
    significance: 'Karnataka: Direct parallel to Huli Vesha (Tiger Masque) of Tulu Nadu.',
    seasonal_markers: ['Onam', 'September'],
    related_traditions: [],
    tags: ['tiger', 'body-art', 'carnival'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },

  // --- 3. FOOD & DRINK ---
  {
    id: 'ev_sadya',
    name: 'Sadya',
    location: { lat: 9.59, lng: 76.52, region: 'All Kerala' },
    type: 'custom',
    category: 'Food',
    description: 'Vegetarian feast on banana leaf; 20+ dishes.',
    significance: 'South India: Part of the broader South Indian leaf-meal tradition, but unique dishes.',
    seasonal_markers: ['Onam', 'Weddings'],
    related_traditions: [],
    tags: ['feast', 'vegetarian', 'communal'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_appam',
    name: 'Appam',
    location: { lat: 9.93, lng: 76.26, region: 'Kerala' },
    type: 'custom',
    category: 'Food',
    description: 'Fermented rice pancake made in a curved pan (Appachatti).',
    significance: 'Sri Lanka: Identical to Hoppers (Appa); mentioned in Sangam literature.',
    seasonal_markers: ['Breakfast'],
    related_traditions: [],
    tags: ['breakfast', 'rice', 'fermented'],
    emotional_resonance: 'medium',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_puttu',
    name: 'Puttu',
    location: { lat: 10.0, lng: 76.3, region: 'Kerala' },
    type: 'custom',
    category: 'Food',
    description: 'Steamed rice cake in bamboo/metal log.',
    significance: 'Southeast Asia: Technological link to Putu Bambu (Indonesia/Malaysia).',
    seasonal_markers: ['Breakfast'],
    related_traditions: [],
    tags: ['steamed', 'breakfast', 'coconut'],
    emotional_resonance: 'medium',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_malabar_biryani',
    name: 'Malabar Biryani',
    location: { lat: 11.25, lng: 75.78, region: 'Kozhikode' },
    type: 'custom',
    category: 'Food',
    description: 'Spiced rice-meat dish using Kaima rice and "Dum" method.',
    significance: 'Persia/Yemen: Derived from Pilaf/Mandi via Arab traders.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['biryani', 'muslim', 'spicy'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_suleimani',
    name: 'Suleimani',
    location: { lat: 11.25, lng: 75.77, region: 'Malabar Tea Stalls' },
    type: 'custom',
    category: 'Drink',
    description: 'Black tea with lemon and spices.',
    significance: 'Arabia: Named after "Sulaiman" (Solomon) or peace; Arab trade influence.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['tea', 'black-tea', 'arab'],
    emotional_resonance: 'medium',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_karimeen',
    name: 'Karimeen Pollichathu',
    location: { lat: 9.49, lng: 76.33, region: 'Alappuzha' },
    type: 'custom',
    category: 'Food',
    description: 'Pearl Spot fish marinated and roasted in banana leaf.',
    significance: 'Polynesia/SE Asia: Cooking in leaves is a pan-tropical technique.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['seafood', 'fish', 'backwaters'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },

  // --- 4. NATURE & GEOGRAPHY ---
  {
    id: 'ev_silent_valley',
    name: 'Silent Valley',
    location: { lat: 11.13, lng: 76.42, region: 'Palakkad' },
    type: 'nature',
    category: 'Geography',
    description: 'Rainforest. Saved by environmental movement.',
    significance: 'Nature: One of the last undisturbed tropical evergreen rainforests in India.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['rainforest', 'ecology', 'biodiversity'],
    emotional_resonance: 'high',
    preservation_score: 90,
    dna_relationships: []
  },
  {
    id: 'ev_periyar',
    name: 'Periyar Reserve',
    location: { lat: 9.46, lng: 77.14, region: 'Thekkady' },
    type: 'nature',
    category: 'Geography',
    description: 'Longest River. Lifeline of Kerala.',
    significance: 'Nature: Elephant sighting by boat. Colonial engineering meets wildlife conservation.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['river', 'wildlife', 'reserve'],
    emotional_resonance: 'medium',
    preservation_score: 85,
    dna_relationships: []
  },
  {
    id: 'ev_edakkal',
    name: 'Edakkal Caves',
    location: { lat: 11.62, lng: 76.23, region: 'Wayanad' },
    type: 'history',
    category: 'Archaeology',
    description: 'Prehistoric rock engravings (petroglyphs).',
    significance: 'Global: Neolithic rock art found globally; indicates early settlement.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['neolithic', 'caves', 'art'],
    emotional_resonance: 'medium',
    preservation_score: 60,
    dna_relationships: []
  },
  {
    id: 'ev_varkala',
    name: 'Varkala Cliff',
    location: { lat: 8.73, lng: 76.70, region: 'Varkala' },
    type: 'nature',
    category: 'Geography',
    description: 'Laterite Cliff. Geology: Geo-heritage site.',
    significance: 'Nature: Unique geological formation on the coast.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['cliff', 'beach', 'geology'],
    emotional_resonance: 'high',
    preservation_score: 75,
    dna_relationships: []
  },

  // --- 5. HISTORY & HERITAGE ---
  {
    id: 'ev_muziris',
    name: 'Muziris (Pattanam)',
    location: { lat: 10.15, lng: 76.20, region: 'Pattanam' },
    type: 'history',
    category: 'Archaeology',
    description: 'Ancient port city; center of the spice trade.',
    significance: 'Rome/Egypt: Part of the "Spice Route" world system (Roman trade).',
    seasonal_markers: ['Excavation'],
    related_traditions: [],
    tags: ['port', 'trade', 'ancient'],
    emotional_resonance: 'low',
    preservation_score: 50,
    dna_relationships: []
  },
  {
    id: 'ev_jew_town',
    name: 'Paradesi Synagogue',
    location: { lat: 9.95, lng: 76.26, region: 'Mattancherry' },
    type: 'history',
    category: 'Heritage',
    description: 'Place of worship for Malabar/Cochin Jews.',
    significance: 'Israel: Direct link to the Jewish Diaspora and Holy Land.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['jewish', 'synagogue', 'history'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_chinese_nets',
    name: 'Chinese Fishing Nets',
    location: { lat: 9.96, lng: 76.24, region: 'Fort Kochi' },
    type: 'custom',
    category: 'Technology',
    description: 'Cantilevered fishing nets (Cheena Vala).',
    significance: 'China: Introduced by Zheng He\'s fleet or Kublai Khan\'s traders.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['fishing', 'technology', 'chinese'],
    emotional_resonance: 'high',
    preservation_score: 60,
    dna_relationships: []
  },
  {
    id: 'ev_padmanabhapuram',
    name: 'Padmanabhapuram Palace',
    location: { lat: 8.25, lng: 77.31, region: 'Thuckalay' },
    type: 'history',
    category: 'Architecture',
    description: 'Wooden Palace of Travancore. Masterpiece of timber architecture.',
    significance: 'Arch: Masterpiece of Kerala timber architecture (Thatchu Shastra).',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['palace', 'wood', 'architecture'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_bekal',
    name: 'Bekal Fort',
    location: { lat: 12.38, lng: 75.03, region: 'Kasaragod' },
    type: 'history',
    category: 'Architecture',
    description: 'Coastal Fort (Laterite). Largest fort in Kerala.',
    significance: 'Defense: Keyhole observation posts. Coastal defense.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['fort', 'defense', 'history'],
    emotional_resonance: 'medium',
    preservation_score: 90,
    dna_relationships: []
  },

  // --- 6. FESTIVALS ---
  {
    id: 'ev_thrissur_pooram',
    name: 'Thrissur Pooram',
    location: { lat: 10.52, lng: 76.21, region: 'Thrissur' },
    type: 'festival',
    category: 'Festival',
    description: 'Massive temple festival with elephants and fireworks.',
    significance: 'Pageantry: Rivalry between temples (Matsaram); grand spectacle.',
    seasonal_markers: ['April-May'],
    related_traditions: [],
    tags: ['elephants', 'fireworks', 'percussion'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_attukal',
    name: 'Attukal Pongala',
    location: { lat: 8.49, lng: 76.95, region: 'Trivandrum' },
    type: 'festival',
    category: 'Festival',
    description: 'Largest gathering of women; cooking offering to Goddess.',
    significance: 'Feminine Divine: "Sabarimala of Women"; massive communal cooking.',
    seasonal_markers: ['February'],
    related_traditions: [],
    tags: ['women', 'pongala', 'goddess'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_ochira',
    name: 'Ochira Kali',
    location: { lat: 9.20, lng: 76.50, region: 'Ochira' },
    type: 'festival',
    category: 'Festival',
    description: 'Mock battle in mud. Commemorates historic battle.',
    significance: 'Martial: Commemorates historic battle between Kayamkulam and Chempakassery.',
    seasonal_markers: ['June'],
    related_traditions: ['ev_kalaripayattu'],
    tags: ['martial', 'mud', 'battle'],
    emotional_resonance: 'high',
    preservation_score: 80,
    dna_relationships: []
  },
  {
    id: 'ev_mamankam',
    name: 'Mamankam (Historic)',
    location: { lat: 10.86, lng: 75.99, region: 'Tirunavaya' },
    type: 'history',
    category: 'State Ritual',
    description: '12-year festival of trade and martial suicide (Chaver).',
    significance: 'Bali: Resembles the "Theatre State" rituals described by Geertz.',
    seasonal_markers: ['Extinct'],
    related_traditions: [],
    tags: ['extinct', 'martial', 'feud'],
    emotional_resonance: 'low',
    preservation_score: 10,
    dna_relationships: []
  },

  // --- 7. TRIBES & COMMUNITIES ---
  {
    id: 'ev_muthuvan',
    name: 'Muthuvan Tribe',
    location: { lat: 10.08, lng: 77.06, region: 'Idukki/Munnar' },
    type: 'community',
    category: 'Tribe',
    description: 'High-range tribe; carry children on backs (Muthu).',
    significance: 'Migration: Legend links them to Madurai dynasty migration.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['tribe', 'high-range', 'migration'],
    emotional_resonance: 'medium',
    preservation_score: 60,
    dna_relationships: []
  },
  {
    id: 'ev_kurichya',
    name: 'Kurichya Tribe',
    location: { lat: 11.60, lng: 76.00, region: 'Wayanad' },
    type: 'community',
    category: 'Tribe',
    description: 'Matrilineal warrior tribe (fought British).',
    significance: 'Martial: Skilled archers; aided Pazhassi Raja.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['tribe', 'warrior', 'archery'],
    emotional_resonance: 'high',
    preservation_score: 70,
    dna_relationships: []
  },
  {
    id: 'ev_cholanaickan',
    name: 'Cholanaickan',
    location: { lat: 11.27, lng: 76.24, region: 'Nilambur Forests' },
    type: 'community',
    category: 'Tribe',
    description: '"Cave men" of Kerala; hunter-gatherers.',
    significance: 'Pre-historic: One of the most primitive tribal groups in India.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['tribe', 'hunter-gatherer', 'cave'],
    emotional_resonance: 'medium',
    preservation_score: 40,
    dna_relationships: []
  },
  {
    id: 'ev_cochin_jews',
    name: 'Cochin Jews',
    location: { lat: 9.95, lng: 76.26, region: 'Jew Town, Kochi' },
    type: 'community',
    category: 'Community',
    description: 'Ancient Jewish diaspora. Oldest Jewish group in India.',
    significance: 'Diaspora: Evidence of gene flow 470-730 years ago; genetic link to Knanaya.',
    seasonal_markers: ['Extinct (Mostly)'],
    related_traditions: [],
    tags: ['jewish', 'diaspora', 'community'],
    emotional_resonance: 'high',
    preservation_score: 20,
    dna_relationships: []
  },

  // --- 8. OBJECTS & CRAFTS ---
  {
    id: 'ev_aranmula_kannadi',
    name: 'Aranmula Kannadi',
    location: { lat: 9.33, lng: 76.68, region: 'Aranmula' },
    type: 'custom',
    category: 'Craft',
    description: 'Metal-alloy mirrors made with secret composition.',
    significance: 'Ancient World: Metal mirrors predate glass; rare survival of ancient metallurgy.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['mirror', 'metallurgy', 'craft'],
    emotional_resonance: 'medium',
    preservation_score: 75,
    dna_relationships: []
  },
  {
    id: 'ev_snake_boat',
    name: 'Snake Boat (Chundan)',
    location: { lat: 9.49, lng: 76.33, region: 'Alleppey' },
    type: 'custom',
    category: 'Object/Tradition',
    description: 'Long war canoes used in races (Vallam Kali).',
    significance: 'China/SE Asia: Strong parallels with Dragon Boat racing traditions.',
    seasonal_markers: ['August-September'],
    related_traditions: [],
    tags: ['boat', 'race', 'war-canoe'],
    emotional_resonance: 'high',
    preservation_score: 95,
    dna_relationships: []
  },
  {
    id: 'ev_nettur_petti',
    name: 'Nettur Petti',
    location: { lat: 11.25, lng: 75.77, region: 'Malabar' },
    type: 'custom',
    category: 'Craft',
    description: 'Traditional jewelry box with brass/copper fittings.',
    significance: 'Colonial: Influenced by colonial chest designs but indigenous aesthetic.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['jewelry', 'box', 'craft'],
    emotional_resonance: 'low',
    preservation_score: 60,
    dna_relationships: []
  },
  {
    id: 'ev_beypore_uru',
    name: 'Beypore Uru',
    location: { lat: 11.16, lng: 75.80, region: 'Beypore' },
    type: 'custom',
    category: 'Craft',
    description: 'Wooden ship (Dhow) building.',
    significance: 'Trade: Arab trade vessel building. Links Kerala to the "Great Arab Lake" of trade.',
    seasonal_markers: ['Year-round'],
    related_traditions: [],
    tags: ['ship', 'dhow', 'trade'],
    emotional_resonance: 'medium',
    preservation_score: 50,
    dna_relationships: []
  },

  // --- 9. PEOPLE & LEGENDS (Mapped to locations) ---
  {
    id: 'ev_raja_ravi_varma',
    name: 'Raja Ravi Varma',
    location: { lat: 8.76, lng: 76.90, region: 'Kilimanoor Palace' },
    type: 'person',
    category: 'Person',
    description: 'Painter; modernized Indian art. Realistic oil painting of Indian mythology.',
    significance: 'Art: Realistic oil painting of Indian mythology. Cultural icon.',
    seasonal_markers: [],
    related_traditions: [],
    tags: ['art', 'painter', 'modern'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_kunchan_nambiar',
    name: 'Kunchan Nambiar',
    location: { lat: 9.38, lng: 76.35, region: 'Ambalapuzha' },
    type: 'person',
    category: 'Person',
    description: 'Poet/Satirist; invented Thullal.',
    significance: 'Literature: Father of satirical Malayalam poetry. Invented Ottamthullal.',
    seasonal_markers: [],
    related_traditions: ['ev_ottamthullal'],
    tags: ['poet', 'satire', 'literature'],
    emotional_resonance: 'medium',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_pazhassi_raja',
    name: 'Pazhassi Raja',
    location: { lat: 11.80, lng: 76.00, region: 'Mananthavady' },
    type: 'person',
    category: 'Person',
    description: 'Lion of Kerala; guerilla warfare. Fought British in Wayanad forests.',
    significance: 'War: Aided by Kurichya tribe. Symbol of resistance.',
    seasonal_markers: [],
    related_traditions: ['ev_kurichya'],
    tags: ['warrior', 'king', 'resistance'],
    emotional_resonance: 'high',
    preservation_score: 100,
    dna_relationships: []
  },
  {
    id: 'ev_parasurama',
    name: 'Parasurama (Legend)',
    location: { lat: 10.52, lng: 76.21, region: 'All Kerala' },
    type: 'history',
    category: 'Legend',
    description: 'Creator of Kerala (threw axe into sea).',
    significance: 'Myth: Origin myth justifying Brahmin land ownership.',
    seasonal_markers: [],
    related_traditions: [],
    tags: ['myth', 'origin', 'legend'],
    emotional_resonance: 'medium',
    preservation_score: 100,
    dna_relationships: []
  }
];

export const useDataProvider = () => {
  const getCulturalEvents = (filter?: string) => {
    if (!filter) return CULTURAL_EVENTS;
    return CULTURAL_EVENTS.filter(e => e.type === filter);
  };

  const getEventById = (id: string) => {
    return CULTURAL_EVENTS.find(e => e.id === id);
  };

  const getRelatedEvents = (id: string) => {
    const event = getEventById(id);
    if (!event) return [];
    return CULTURAL_EVENTS.filter(e => event.related_traditions.includes(e.id));
  };

  return {
    events: CULTURAL_EVENTS,
    getCulturalEvents,
    getEventById,
    getRelatedEvents
  };
};